name: Scrape Bitcoin Value and Store in DynamoDB

on:
  schedule:
    # Runs every 5 minutes (GitHub Actions minimum frequency)
    - cron: "*/2 * * * *"
  workflow_dispatch:  # manual trigger option

jobs:
  scrape-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 boto3

      - name: Run scrape_and_store.py
        run: python scrape_and_store.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
